/** Dependency-free initial browser control surface for the shared RPC backend. */
export const HEADLESS_PAGE = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Klerm Server</title><style>
body{font:16px system-ui;background:#10131b;color:#e7eaf1;max-width:1100px;margin:32px auto;padding:0 20px}section{background:#1b2030;padding:20px;margin:16px 0;border-radius:12px}input,select,textarea,button{font:inherit;background:#10131b;color:inherit;border:1px solid #596174;border-radius:6px;padding:10px;margin:4px}textarea{box-sizing:border-box;width:100%;min-height:100px}button{cursor:pointer;background:#283956}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:450px;overflow:auto}label{display:inline-block}#status{color:#a8c7ff}.row{display:flex;flex-wrap:wrap;gap:8px}h1,h2{margin-top:0}small{color:#bac2d1}
</style></head><body><h1>Klerm Server</h1><p id="status">Connect with the owner token. Tasks belong to the server and continue when this page closes.</p>
<section><label>Owner token <input id="token" type="password" autocomplete="off"></label><button id="connect">Connect</button><button id="disconnect">Disconnect</button></section>
<section><h2>Installed harnesses</h2><button id="refresh">Refresh discovery</button><pre id="harnesses">Not connected</pre></section>
<section><h2>Agents</h2><small>Configure a native Hermes Build worker here, or edit the shared slot configuration below. Full access applies to this worker's OS/container permissions.</small>
<div class="row"><label>Agent <select id="agent"><option>agent1</option><option>agent2</option><option>agent3</option><option>agent4</option></select></label><label>Hermes model <input id="model" value="native-default"></label><label>Profile <select id="profile"><option value="native">Native (permission requests denied)</option><option value="full-access">Full access</option></select></label><button id="hermes">Configure Hermes</button></div>
<button id="loadSlots">Load agent configuration</button><button id="saveSlots">Save agent configuration</button><textarea id="slots" aria-label="Agent configuration JSON"></textarea></section>
<section><h2>Conversation</h2><textarea id="prompt" placeholder="Ask the selected agent to work in the server workspace" aria-label="Task prompt"></textarea><button id="send">Send to selected agent</button><button id="stop">Stop task</button><button id="state">Refresh state</button><button id="messages">Load messages</button><div id="approvals"></div><pre id="feed"></pre></section>
<section><h2>Klerm Kanban</h2><small>The shared backend supports built-in Personal Agent cards and its existing repeat-minute scheduler. Native Hermes Kanban/cron is separate; shared external-agent assignment is a later slice.</small><div><button id="loadBoard">Load boards</button><button id="saveBoard">Save boards</button><label>Board ID <input id="boardId"></label><label>Task ID <input id="taskId"></label><button id="runCard">Run card</button><button id="stopCard">Stop card</button></div><textarea id="boards" aria-label="Kanban registry JSON"></textarea></section>
<section><h2>Typed backend commands</h2><small>Use the same supported RPC commands for browser, MCP, workspace and model operations. Native-only browser surfaces are not provided by this page. New IDs are generated per explicit submission.</small><textarea id="command" aria-label="Backend command JSON">{"type":"get_browser_availability"}</textarea><button id="execute">Execute command</button><pre id="result"></pre></section>
<script>
const el=id=>document.getElementById(id);let token='',streamAbort,cursor='';
function show(value){el('result').textContent=JSON.stringify(value,null,2)}
function append(value){if(value.type==='extension_ui_request')approval(value);const feed=el('feed');feed.textContent=(feed.textContent+'\n'+JSON.stringify(value)).slice(-100000);feed.scrollTop=feed.scrollHeight}
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data}
async function command(value){const data=await api('/api/command',{...value,id:value.id??crypto.randomUUID()});show(data);if(data.success===false)throw Error(data.error||'Backend command failed');return data}
function approval(event){if(event.method!=='confirm'||document.getElementById('approval-'+event.id))return;const box=document.createElement('div');box.id='approval-'+event.id;const title=document.createElement('p');title.textContent=(event.title||'Approval')+' '+(event.message||'');box.append(title);for(const confirmed of [true,false]){const button=document.createElement('button');button.textContent=confirmed?'Approve':'Deny';button.onclick=async()=>{try{await command({type:'extension_ui_response',id:event.id,confirmed});box.remove()}catch(error){el('status').textContent=error.message}};box.append(button)}el('approvals').append(box)}
async function loadSlots(){const data=await command({type:'get_coding_harness_setup'});el('slots').value=JSON.stringify(data.data.slots,null,2);return data.data.slots}
function bind(id,action){el(id).onclick=()=>Promise.resolve().then(action).catch(error=>{el('status').textContent=error.message})}
async function stream(){streamAbort?.abort();const control=new AbortController();streamAbort=control;
while(!control.signal.aborted){try{const response=await fetch('/api/events',{headers:{Authorization:'Bearer '+token,...(cursor?{'Last-Event-ID':cursor}:{})},signal:control.signal});if(!response.ok)throw Error('Event stream authentication failed');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const next=await reader.read();if(next.done)break;buffer+=decoder.decode(next.value,{stream:true});let end;while((end=buffer.indexOf('\n\n'))>=0){const frame=buffer.slice(0,end);buffer=buffer.slice(end+2);for(const line of frame.split('\n')){if(line.startsWith('id: '))cursor=line.slice(4);if(line.startsWith('data: ')){const event=JSON.parse(line.slice(6));if(event.type==='stream_reset'){cursor='';el('status').textContent=event.reason}append(event)}}}}}catch(error){if(control.signal.aborted)return;el('status').textContent=error.message}await new Promise(resolve=>setTimeout(resolve,2000))}}
bind('connect',async()=>{token=el('token').value.trim();el('token').value='';const data=await api('/api/harnesses');el('harnesses').textContent=JSON.stringify(data.harnesses,null,2);await loadSlots();el('status').textContent='Connected. Owner token stays in page memory only.';void stream()});
bind('disconnect',()=>{streamAbort?.abort();token='';cursor='';el('status').textContent='Disconnected. Running tasks remain on the server.'});
bind('refresh',async()=>{const data=await api('/api/refresh',{});el('harnesses').textContent=JSON.stringify(data.harnesses,null,2)});
bind('loadSlots',loadSlots);bind('saveSlots',()=>command({type:'set_coding_harness_slots',slots:JSON.parse(el('slots').value)}));
bind('hermes',async()=>{const slots=await loadSlots();slots.externalHarnessesEnabled=true;const agent={id:el('agent').value,kind:'hermes',enabled:true,model:el('model').value.trim(),role:'builder',effort:'off',tools:[],executionProfile:el('profile').value};const index=slots.agents.findIndex(value=>value.id===agent.id);if(index>=0)slots.agents[index]=agent;else slots.agents.push(agent);await command({type:'set_coding_harness_slots',slots});await loadSlots()});
bind('send',()=>command({type:'prompt',targetAgentId:el('agent').value,message:el('prompt').value}));bind('stop',()=>command({type:'abort'}));bind('state',()=>command({type:'get_state'}));bind('messages',()=>command({type:'get_messages'}));
bind('loadBoard',async()=>{const data=await command({type:'get_kanban_registry'});el('boards').value=JSON.stringify(data.data.registry??data.data,null,2)});bind('saveBoard',()=>command({type:'set_kanban_registry',registry:JSON.parse(el('boards').value)}));
bind('runCard',()=>command({type:'run_kanban_task',boardId:el('boardId').value,taskId:el('taskId').value}));bind('stopCard',()=>command({type:'stop_kanban_task',boardId:el('boardId').value,taskId:el('taskId').value}));bind('execute',()=>command(JSON.parse(el('command').value)));
</script></body></html>`;
